[package]
name = "haproxy_simple_module"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
haproxy-api = { path = "../.." }
mlua = { version = "0.9", features = ["macros"] }
